cask "aerospace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version "0.20.3-Beta-cotton.5"
  sha256 "3d41e28d85adb6f92e11edbe299e1d80647f843ad98c97f4d5703577a8bd5ba6"

  url "https://github.com/quanganhdo/Aerospace/releases/download/v#{version}/AeroSpace-v#{version}.zip"
  name "AeroSpace"
  desc "Tiling window manager with i3-like commands and dwindle layout"
  homepage "https://github.com/quanganhdo/Aerospace"

  conflicts_with cask: "aerospace-dev"
  depends_on macos: :ventura

  app "AeroSpace-v#{version}/AeroSpace.app"
  binary "AeroSpace-v#{version}/bin/aerospace"
  binary "AeroSpace-v#{version}/shell-completion/zsh/_aerospace",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospace"
  binary "AeroSpace-v#{version}/shell-completion/bash/aerospace",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospace"
  binary "AeroSpace-v#{version}/shell-completion/fish/aerospace.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospace.fish"
  Dir["#{staged_path}/AeroSpace-v#{version}/manpage/*"].each { |man| manpage man }
end
