cask "aerospace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version "0.20.3-Beta-cotton.1"
  sha256 "164c5be3f0616df6cce5e8459f348dd51e4b307d15d0818204f9d05e2cdceb79"

  url "https://github.com/quanganhdo/Aerospace/releases/download/v#{version}/AeroSpace-v#{version}.zip"
  name "AeroSpace"
  desc "Tiling window manager with i3-like commands and dwindle layout"
  homepage "https://github.com/quanganhdo/Aerospace"

  conflicts_with cask: "aerospace-dev"
  depends_on macos: :ventura

  app "AeroSpace-v#{version}/AeroSpace.app"
end
